apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::993051104393:role/EKSClusterRole

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    iam:
      instanceRoleARN: arn:aws:iam::993051104393:role/EKSNodeRole